### ISSUE TITLE
ca-chain attribute should be optional

### ISSUE THREAD

**Issue by grobbie** [canonical/manual-tls-certificates-operator#157]
#### Describe the bug
At the moment, the `ca-chain` attribute of the `provide-certificate` action is mandatory, and requires at least two certificates to be provided. This makes no sense when a private CA service is in play, and makes the charm unusable, since the chain is only the single root cert, which is already provided in the `ca-certificate` atribute.

**Comment by gruyaume** [comment]
Hi @grobbie, thanks for opening this. I agree this should be an optional value, I'll look into this.
