### ISSUE TITLE
Add a hook to notify the clients that there is a CA rotation

### ISSUE THREAD

**Issue by skourta** [canonical/manual-tls-certificates-operator#280]
### Enhancement Proposal

Currently, there is no way to notify the clients of the `manual-tls-certificates` operator that there is a CA rotation taking place. 
A hook to notify the clients that a CA rotation is taking place should be added to trigger the rotation on the client side and request new CSRs.

**Comment by saltiyazan** [comment]
Thanks for openning this issue.

Currently `manual-tls-certificates-operator` is not a CA, it only passes certificates that have been signed by other CAs to requirer charms, it has no knowledge of the CAs that signed the certificates it passes to the requirer. In the future we might consider some ideas like monitoring CRLs but this not yet planned or designed.

**Comment by gruyaume** [comment]
Closing this issue since this is not a possibility, as Yazan outlined above.
