### ISSUE TITLE
[RFE] tls-certificates-operator should have default integration with COS

### ISSUE THREAD

**Issue by phvalguima** [canonical/manual-tls-certificates-operator#60]
Certificate management demands a continuous monitoring of all the certificates provided. The operator should have an integration with COS alertmanager and provide the following alerts:
* per certificate (incl. CAs): WARN if certificate is expiring
* per certificate (incl. CAs): CRIT if certificate was invalidated or expired and no replacement presented

**Comment by gruyaume** [comment]
Before sending any alerts, we should evaluate the possibility of generating metrics and having those scraped by Prometheus. In contrast with most charms, this one does not contain any workload and I would like to keep this aspect as is as it makes the charm work on both machine and k8s environments.

**Comment by gruyaume** [comment]
At the moment, it seems like the most reasonable approach for such usecases is to leverage [Prometheus Push Gateway](https://charmhub.io/prometheus-pushgateway-k8s). To implement this we would need to:
- Implement the `pushgateway` integration in this charm and send metrics for `certificate_requests` and probably others
- Update the documentation to show users how to integrate tls-certificates-operator with COS

Here's the integration API documentation: 
- https://github.com/canonical/prometheus-pushgateway-k8s-operator/blob/main/lib/charms/prometheus_pushgateway_k8s/v0/pushgateway.py

**Comment by phvalguima** [comment]
Hi @gruyaume that makes sense

**Comment by ghislainbourgeois** [comment]
I also agree with this approach, once we provide metrics, it will make it easier to also provide alerts on many aspects of the operations.

The Push Gateway is also the right tool for this job.

**Comment by gruyaume** [comment]
@simskij There is no workload in this charm, how would you do this?

**Comment by gruyaume** [comment]
We will start with charm tracing instead of metrics for workload-less charms (manual-tls-certificates and self-signed-certificates).

Metrics for workload-less charms is not something that have been figured out anywhere in the charm ecosystem.
