### ISSUE TITLE
[RFE] Accept third-party CAs to be trusted by all related units

### ISSUE THREAD

**Issue by phvalguima** [canonical/manual-tls-certificates-operator#61]
There are two very common scenarios where we need to inject third party CAs on all units at once:
1) SSLBump proxy: a proxy acts as a MITM and generates certificates using its own CA to sign off for each HTTPS connection
2) mTLS support: we may need to add extra CAs from other PKIs to be trusted for a mTLS connection

These CAs should be managed the same way as the other CAs (i.e. generating events and alerts if one of the CAs will expire)

**Comment by gruyaume** [comment]
This feature request is not clear to me, what exactly is required from this operator to satisfy your needs?

**Comment by gruyaume** [comment]
@phvalguima can you please answer my comment above?

**Comment by phvalguima** [comment]
Hi @gruyaume, we need 2x config options, e.g. "extra-CAs" and "automatic-update-ca-certificates", where I can add extra CAs to all the units at once that have nothing to do with the CSRs / certificates managed by tls-certificates-operator.

For example:
```
juju config automatic-update-ca-certificates=True  # Defaults to False, as we may not need it; if set to True, then manage these CAs in the /etc/ssl/certificates and run update-ca-certificates command on that host

juju config tls-certificates-operator extra-cas="----- BEGIN CERTIFICATE -----
....
....
....
----- END CERTIFICATE -----
----- BEGIN CERTIFICATE -----
....
....
....
----- END CERTIFICATE -----
....
----- BEGIN CERTIFICATE -----
....
....
....
----- END CERTIFICATE -----"
```


Originally, an user would manage certificates for something like SSLBump proxy by injecting those certs using Juju's cloud-init userdata. That is enough to bootstrap and deploy, but cloud-init only takes effect at node boot. Updating the cloud-init also means rebooting the node.

The mTLS is another scenario: I may have to accept multiple PKIs and different CA chains for the mTLS.

Another option is to just run `update-ca-certificates` manually. However, every new unit, we need to remember that.

My recommendation would be the tls-certificates-operator must:
1) Receive the CAs from the config
2) pass it through the validations that we run for every certificate / CA
3) If the user chooses: manage the certificates with update-ca-certificates command
4) Make these extra CAs available to any application related to this charm

## Example for SSL Bump proxy

In this scenario, we would start by using the cloud-init to get the cluster bootstrap correctly. Here is the step-by-step:
```
# CREATE THE CLOUD INIT WITH THE SSL BUMP CERTIFICATES
$ juju bootstrap my-cloud my-controller --config cloudinit-userdata=$(cat ./cloud-init.yaml)
$ juju add-model --model-config cloudinit-userdata=$(cat ./cloud-init.yaml)

# ... Deploy all your cool apps
# The logic above will inject the certificates in the cloud-init

$ juju deploy tls-certificates-operator automatic-update-ca-certificates=True extra-cas=".... SAME CAs FROM CLOUD-INIT"
$ juju integrate tls-certificates-operator your-cool-app(s)

# Do the same in the controller model, so we can also manage the certificates in that env
```

Now, we can use tls-certificates-operator for the entire lifetime of the application. The only extra step in this case is: every time we rotate the SSL Bump CA, then we need to update the tls-certificates operator AND the cloud-init script

## Example for mTLS

In this scenario, we do not need to know the extra CAs at deployment time and these CAs only matter for the target-application. That means we do not need tls-certificates-operator to inject the CAs using update-ca-certificates command.
```
$ juju deploy tls-certificates-operator automatic-update-ca-certificates=False extra-cas="...."
$ juju integrate tls-certificates-operator your-cool-app(s)
```

**Comment by gruyaume** [comment]
I'm not sure how much I agree with this feature request. Your request is along the line of "We want a store of certificates that charms can relate to to get a list of trusted certificates". While I do understand this need, it's not what TLS Certificates Operator is made for at the moment.

**Comment by grobbie** [comment]
@phvalguima I believe this should be regarded more as a generic Juju defect. Juju supports installing CA files via cloud-init and it works fine on VMs, however it (obviously) doesn't work on K8s.

**Comment by phvalguima** [comment]
Hi @grobbie the issue is the lifecycle post cloud init as well. We need to keep track, remove older and add newer CAs over time.
