### ISSUE TITLE
`get-outstanding-certificate-requests` return value is a Python literal string

### ISSUE THREAD

**Issue by DanielArndt** [canonical/manual-tls-certificates-operator#79]
#### Describe the bug
Value stored in the result of the `get-outstanding-certificate-requests` action is a python literal as a string. This requires the ability to parse the string as Python to programmatically make use of the data.

Using a Python literal string isn't a common format for communicating data. Something like JSON would be a much better fit.

#### To Reproduce

```
juju deploy tls-certificates-requirer --channel edge
juju deploy tls-certificates-operator --channel edge
juju integrate tls-certificates-operator tls-certificates-requirer
juju run tls-certificates-operator/0 get-outstanding-certificate-requests --format=json 2>/dev/null | jq '."tls-certificates-operator/0".results.result'
```

Result is

```
[{'relation_id': 0, 'application_name': 'tls-certificates-requirer', 'unit_name': 'tls-certificates-requirer/0', 'unit_csrs': [{'certificate_signing_request': '-----BEGIN CERTIFICATE REQUEST-----<content>-----END CERTIFICATE REQUEST-----'}]}]"
````

which looks like JSON, but it isn't

```
juju run tls-certificates-operator/0 get-outstanding-certificate-requests --format=json 2>/dev/null | jq '."tls-certificates-operator/0".results.result | fromjson' # Get the result, parse it as JSON
```

The above throws an error.

#### Expected behavior
Expected a common format for the result output.

This data should likely be in JSON format, since [the certificates data is already in JSON](https://github.com/canonical/manual-tls-certificates-operator/blob/rev50/lib/charms/tls_certificates_interface/v2/tls_certificates.py#L969).

#### Environment

- charm version: 50

**Comment by gruyaume** [comment]
Closed by #82
